CREATE TABLE IF NOT EXISTS gw_registration_groups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  group_token VARCHAR(64) NOT NULL,
  public_slug VARCHAR(16) NOT NULL,
  first_name VARCHAR(100) DEFAULT NULL,
  last_name VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  customer_email VARCHAR(200) DEFAULT NULL,
  personal_id VARCHAR(20) DEFAULT NULL,
  branch_id INT DEFAULT NULL,
  registered_by INT DEFAULT NULL,
  served_by INT DEFAULT NULL,
  item_count SMALLINT NOT NULL DEFAULT 0,
  marketing_consent TINYINT NOT NULL DEFAULT 0,
  signed_at DATETIME DEFAULT NULL,
  signature_path VARCHAR(300) DEFAULT NULL,
  signed_by_name VARCHAR(200) DEFAULT NULL,
  signature_ip VARCHAR(45) DEFAULT NULL,
  signature_user_agent VARCHAR(500) DEFAULT NULL,
  sms_sent_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_grp_token (group_token),
  UNIQUE KEY uniq_grp_slug (public_slug),
  KEY idx_grp_phone (phone),
  KEY idx_grp_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
